/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.7.0
 *
 * Project: 'blinky.release+E1C' 
 * Target:  'release+E1C' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M55_HE.h"

/* ARM::CMSIS-Compiler:I/O:STDIN&User@1.0.0 */
#define RTE_Compiler_IO_STDIN           /* Compiler I/O: STDIN */
#define RTE_Compiler_IO_STDIN_User      /* Compiler I/O: STDIN User */
/* ARM::CMSIS-Compiler:I/O:STDOUT&User@1.0.0 */
#define RTE_Compiler_IO_STDOUT          /* Compiler I/O: STDOUT */
#define RTE_Compiler_IO_STDOUT_User     /* Compiler I/O: STDOUT User */
/* AlifSemiconductor::Device:Power Management@1.3.0 */
#define RTE_PM   1           /* Power Management */
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@1.1.0 */
#define RTE_Drivers_GPIO   1           /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@1.1.0 */
#define RTE_Drivers_LL_PINCONF   1           /* Driver PinPAD and PinMux */
/* AlifSemiconductor::Device:SOC Peripherals:USART@1.1.0 */
#define RTE_Drivers_USART0   1           /* Driver UART0 */
#define RTE_Drivers_USART1   1           /* Driver UART1 */
#define RTE_Drivers_USART2   1           /* Driver UART2 */
#define RTE_Drivers_USART3   1           /* Driver UART3 */
#define RTE_Drivers_USART4   1           /* Driver UART4 */
#define RTE_Drivers_USART5   1           /* Driver UART5 */


#endif /* RTE_COMPONENTS_H */
